// Theme configurations for the How It Works section

import { ProcessTheme } from './types';

export const kidsProcessTheme: ProcessTheme = {
  variant: 'kids',
  colors: {
    background: '#F8FAFC',
    backgroundAlt: '#EFF6FF',
    card: '#FFFFFF',
    progressBar: '#E2E8F0',
    progressFill: '#1E293B',
    progressIndicator: '#A5B4FC',
    text: '#1E293B',
    textMuted: '#64748B',
    accent: '#A5B4FC',
    accentText: '#4F46E5',
    pricingBg: '#1E293B',
    pricingCard: '#FFFFFF',
    pricingCardAlt: '#F1F5F9',
  },
  sectionTitle: 'How the Magic Happens',
  sectionSubtitle: 'From imagination to a real book in your hands',
  steps: [
    {
      id: 'step-1',
      number: '/01/',
      title: 'Choose Your Hero',
      subtitle: 'Every great story starts with a character',
      description: 'Upload a photo of your little one and watch them transform into the star of their very own adventure. Our AI captures their unique features to create a personalized character.',
      bulletPoints: [
        'Upload any clear face photo',
        'AI creates a custom illustrated character',
        'Choose from boy, girl, or custom styles',
        'Preview your hero instantly',
      ],
      illustration: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-2',
      number: '/02/',
      title: 'Magic Cover Preview',
      subtitle: 'See the magic come to life — for free',
      description: 'Before you commit, we generate a stunning book cover featuring your child as the main character. This preview is completely free and shows you exactly what to expect.',
      bulletPoints: [
        'Free AI-generated cover preview',
        'Multiple style options to choose from',
        'See your child as the hero',
        'No payment required to preview',
      ],
      illustration: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-3',
      number: '/03/',
      title: 'Customize Your Story',
      subtitle: 'Make it uniquely theirs',
      description: 'Tweak the story to match your child\'s personality. Add their name, choose the adventure theme, include friends or family members, and personalize every detail.',
      bulletPoints: [
        'Personalize names and characters',
        'Choose adventure themes (space, ocean, forest)',
        'Add dedications and special messages',
        'Select illustration styles',
      ],
      illustration: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-4',
      number: '/04/',
      title: 'We Work Our Magic',
      subtitle: 'Our illustrators bring your story to life',
      description: 'Once you\'re happy with your choices, our team of AI-assisted illustrators creates every page of your book. Each illustration is crafted to maintain consistency and quality.',
      bulletPoints: [
        'AI-powered illustration generation',
        'Human quality review process',
        'Consistent character appearance',
        'Professional book layout',
      ],
      illustration: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-5',
      number: '/05/',
      title: 'Delivered to Your Door',
      subtitle: 'A treasure that lasts forever',
      description: 'Your finished book is printed on premium paper with a beautiful hardcover finish. We ship worldwide with tracking, and it arrives ready to become a cherished keepsake.',
      bulletPoints: [
        'Premium hardcover printing',
        'Worldwide shipping with tracking',
        'Gift wrapping available',
        'Satisfaction guaranteed',
      ],
      illustration: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&auto=format&fit=crop&q=60',
    },
  ],
  pricing: {
    title: 'Simple and affordable price.',
    subtitle: 'No funny hidden fees.',
    tiers: [
      {
        id: 'basic',
        name: 'Adventurer',
        features: [
          '12 illustrated pages',
          'Softcover finish',
          'Digital PDF included',
          'Standard shipping',
          'One revision',
        ],
        ctaText: 'Start now',
      },
      {
        id: 'popular',
        name: 'Explorer',
        popular: true,
        features: [
          'All Adventurer features +',
          '24 illustrated pages',
          'Premium hardcover',
          'Priority shipping',
          'Three revisions',
          'Gift wrapping',
        ],
        ctaText: 'Start now',
      },
    ],
  },
};

export const valentinesProcessTheme: ProcessTheme = {
  variant: 'valentines',
  colors: {
    background: '#FFF1F2',
    backgroundAlt: '#FCE7F3',
    card: '#FFFFFF',
    progressBar: '#FECDD3',
    progressFill: '#881337',
    progressIndicator: '#F43F5E',
    text: '#881337',
    textMuted: '#BE123C',
    accent: '#F43F5E',
    accentText: '#E11D48',
    pricingBg: '#881337',
    pricingCard: '#FFFFFF',
    pricingCardAlt: '#FFF1F2',
  },
  sectionTitle: 'How Your Love Story Unfolds',
  sectionSubtitle: 'From your photos to a romantic keepsake',
  steps: [
    {
      id: 'step-1',
      number: '/01/',
      title: 'Share Your Story',
      subtitle: 'Every love story is unique',
      description: 'Upload your favorite couple photos and tell us about your journey together. The more details you share, the more personalized your book becomes.',
      bulletPoints: [
        'Upload your best couple photos',
        'Share your love story highlights',
        'Include special dates and places',
        'Add inside jokes and memories',
      ],
      illustration: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-2',
      number: '/02/',
      title: 'Preview Your Cover',
      subtitle: 'See the romance take shape — free',
      description: 'We create a beautiful romantic cover featuring you both. This preview is completely free and shows the quality and style you can expect.',
      bulletPoints: [
        'Free romantic cover preview',
        'Multiple artistic styles',
        'See yourselves as illustrated characters',
        'No commitment required',
      ],
      illustration: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-3',
      number: '/03/',
      title: 'Personalize Every Detail',
      subtitle: 'Make it truly yours',
      description: 'Customize your love story with special chapters, memorable quotes, and personal touches. Choose the tone — funny, romantic, or a mix of both.',
      bulletPoints: [
        'Write custom dedications',
        'Choose romantic or playful tone',
        'Add milestone chapters',
        'Include your song lyrics or vows',
      ],
      illustration: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-4',
      number: '/04/',
      title: 'Crafted with Love',
      subtitle: 'Our artists create your story',
      description: 'Our team transforms your memories into beautiful illustrations. Each page is designed to capture the essence of your relationship.',
      bulletPoints: [
        'Hand-reviewed illustrations',
        'Consistent romantic style',
        'Professional book design',
        'Quality you can feel',
      ],
      illustration: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-5',
      number: '/05/',
      title: 'A Gift to Remember',
      subtitle: 'Delivered beautifully wrapped',
      description: 'Your love story arrives in elegant gift packaging, ready to surprise your partner. Premium printing ensures it becomes a forever keepsake.',
      bulletPoints: [
        'Luxury hardcover finish',
        'Elegant gift wrapping included',
        'Express shipping available',
        'Arrives before Valentine\'s Day',
      ],
      illustration: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=800&auto=format&fit=crop&q=60',
    },
  ],
  pricing: {
    title: 'Simple and affordable price.',
    subtitle: 'No funny hidden fees.',
    tiers: [
      {
        id: 'basic',
        name: 'Sweetheart',
        features: [
          '12 romantic pages',
          'Softcover finish',
          'Digital PDF included',
          'Standard shipping',
          'One revision',
        ],
        ctaText: 'Start now',
      },
      {
        id: 'popular',
        name: 'Soulmate',
        popular: true,
        features: [
          'All Sweetheart features +',
          '24 romantic pages',
          'Premium hardcover',
          'Express Valentine\'s shipping',
          'Unlimited revisions',
          'Luxury gift box',
        ],
        ctaText: 'Start now',
      },
    ],
  },
};

export const worldcupProcessTheme: ProcessTheme = {
  variant: 'worldcup',
  colors: {
    background: '#ECFDF5',
    backgroundAlt: '#D1FAE5',
    card: '#FFFFFF',
    progressBar: '#A7F3D0',
    progressFill: '#065F46',
    progressIndicator: '#10B981',
    text: '#065F46',
    textMuted: '#059669',
    accent: '#10B981',
    accentText: '#059669',
    pricingBg: '#065F46',
    pricingCard: '#FFFFFF',
    pricingCardAlt: '#ECFDF5',
  },
  sectionTitle: 'Your Path to Glory',
  sectionSubtitle: 'From fan to World Cup champion',
  steps: [
    {
      id: 'step-1',
      number: '/01/',
      title: 'Upload Your Photo',
      subtitle: 'Step onto the world stage',
      description: 'Upload a clear photo of yourself or your child. Our AI will transform you into a professional footballer ready for the biggest stage in world football.',
      bulletPoints: [
        'Upload any clear face photo',
        'AI creates your player avatar',
        'Choose your preferred position',
        'Select your national team',
      ],
      illustration: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-2',
      number: '/02/',
      title: 'Preview Your Cover',
      subtitle: 'See yourself as a champion — free',
      description: 'We create a stunning cover featuring you in the World Cup final. This preview is completely free and shows you the quality of your personalized story.',
      bulletPoints: [
        'Free champion cover preview',
        'See yourself lifting the trophy',
        'Stadium atmosphere included',
        'No payment required to preview',
      ],
      illustration: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-3',
      number: '/03/',
      title: 'Customize Your Journey',
      subtitle: 'Write your own legend',
      description: 'Choose your path to glory. Pick your favorite national team, select key matches, add dramatic moments, and create the World Cup story you\'ve always dreamed of.',
      bulletPoints: [
        'Pick your national team jersey',
        'Choose group stage opponents',
        'Add dramatic penalty shootouts',
        'Include your celebration style',
      ],
      illustration: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-4',
      number: '/04/',
      title: 'We Create Your Story',
      subtitle: 'Every match illustrated',
      description: 'Our team brings your World Cup journey to life with stunning illustrations. From the opening match to lifting the trophy, every moment is captured in beautiful detail.',
      bulletPoints: [
        'Professional match illustrations',
        'Authentic stadium atmospheres',
        'Dramatic goal celebrations',
        'Trophy lifting moment',
      ],
      illustration: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&auto=format&fit=crop&q=60',
    },
    {
      id: 'step-5',
      number: '/05/',
      title: 'Champion Delivery',
      subtitle: 'Your trophy arrives',
      description: 'Your World Cup story is printed on premium paper with a collector\'s edition hardcover. It arrives ready to inspire dreams of footballing glory.',
      bulletPoints: [
        'Collector\'s edition hardcover',
        'Premium glossy paper',
        'Worldwide shipping',
        'Perfect gift for football fans',
      ],
      illustration: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=60',
    },
  ],
  pricing: {
    title: 'Simple and affordable price.',
    subtitle: 'No funny hidden fees.',
    tiers: [
      {
        id: 'basic',
        name: 'Rookie',
        features: [
          '12 illustrated pages',
          'Softcover finish',
          'Digital PDF included',
          'Standard shipping',
          'One revision',
        ],
        ctaText: 'Start now',
      },
      {
        id: 'popular',
        name: 'Legend',
        popular: true,
        features: [
          'All Rookie features +',
          '24 illustrated pages',
          'Collector\'s hardcover',
          'Priority shipping',
          'Three revisions',
          'Certificate of glory',
        ],
        ctaText: 'Start now',
      },
    ],
  },
};

export function getProcessTheme(variant: 'kids' | 'valentines' | 'worldcup'): ProcessTheme {
  if (variant === 'valentines') return valentinesProcessTheme;
  if (variant === 'worldcup') return worldcupProcessTheme;
  return kidsProcessTheme;
}

